agent_2/bt_navigator:
  ros__parameters:
    use_sim_time: True
    global_frame: map
    robot_base_frame: agent_2/base_link
    odom_topic: agent_2/odom
    bt_loop_duration: 10
    default_server_timeout: 20
    enable_groot_monitoring: false